baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'teleportHQ Hugo Site - kustomer katcher'

[module]
[[module.imports]]
    disable = false
    ignoreConfig = false
    ignoreImports = false
    path = 'github.com/dindinet/KustomerKatcher-HTML'
[[module.imports.mounts]]
    source = '.'
    target = 'static'
